### ISSUE TITLE
"hier read" always returns "Today <date> is empty."

### ISSUE THREAD

**Issue by ihtho** [Jessime/hier_client#1]
Hello,
whenever I use `hier read` I get as a return `Today <date> is empty.`
For example I get this today:  `Today (10/10/2019) is empty.`
Despite having written something in today's entry. 

Just for testing purpose I tried `hier write --append "Learned about the Hier client."` and it returns what I have written today + the appended line "Learned about the Hier client."

I used current bash & xfce4-terminal 0.8.8, tried it on rxvt-unicode 9.22-9 too and didn't work there either.

**Comment by Jessime** [comment]
Hey, thanks for letting me know about this! It's fixed now.
